### ISSUE TITLE
fig autocomplete suddenly not working 

### ISSUE THREAD

**Issue by duyhunter1001** [withfig/fig#2522]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.2.1 (21D62)

### Expected behaviour

When type in terminal:

![image](https://github.com/withfig/fig/assets/44033926/a4a57faa-6a7e-41e4-88f4-c6ecb1f0e9fd)

after type space syntax, expected show information popup here:

![image](https://github.com/withfig/fig/assets/44033926/6d3469d8-427a-4cd1-ac09-fb5a806e0cde)

### Actual behaviour

When type in terminal:

![image](https://github.com/withfig/fig/assets/44033926/a4a57faa-6a7e-41e4-88f4-c6ecb1f0e9fd)

after type space syntax, but it doesn't appear popup suggest

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.2.1 (21D62)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/lap15538-local
  - exe-path: /Users/lap15538-local/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 1bf04a34-af9f-42b9-a4fa-bf093ae9cc1b
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/Applications/MAMP/bin/php/php7.4.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/lap15538-local/.fig/bin:/Users/lap15538-local/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 4122
    - FIG_SET_PARENT: 1bf04a34-af9f-42b9-a4fa-bf093ae9cc1b
```

**Comment by oilcake** [comment]
Same here,  MacOS 10.15.7, it just stopped working. Fig doctor responded with error about version, but just once, and looks like it can't be reproduced.

**Comment by duyhunter1001** [comment]
> Same here, MacOS 10.15.7, it just stopped working. Fig doctor responded with error about version, but just once, and looks like it can't be reproduced.

![image](https://github.com/withfig/fig/assets/44033926/21d5e4eb-1f0e-404f-84d2-96d2bcbd4491)
good but not suggest popup.

**Comment by nateshmbhat** [comment]
same here not working for me too 13.0.1 (22A400)

**Comment by WaldoDoesTech** [comment]
Same Here Mac 12.1.1 (21D62)

**Comment by martinteppa** [comment]
Sme macOS 12.2.1 (21D62)

**Comment by rickyadha** [comment]
same macOS 10.15.7 (19H2026)

**Comment by itsalicelee** [comment]
Same here on macOS 13.3.1 (22E772610a)

**Comment by FilipSwiatczak** [comment]
Same here, started today 11th May 2023, Mac Monterey 12.1 21C52 Intel Core i9!

**Comment by mschrage** [comment]
Hey everyone! Thanks for reporting. We are looking into the issue now. We recently added a new CDN and this might have introduced some bug.

**Comment by paulashby** [comment]
Here's the output from the WebView inspector: 

`[Log] [fig] declaring constants... (user-script:4, line 1)
[Log] [fig] setting up event listeners... (index-5919f5c9.js, line 67)
[Log] [fig] unsubscribing any existing notifications... (index-5919f5c9.js, line 67)
[Log] settingsFontSize – undefined (index-5919f5c9.js, line 185)
[Log] applying update: setUserFuzzySearchEnabled (index-5919f5c9.js, line 141)
[Log] applying update: error (index-5919f5c9.js, line 141)
[Warning] Fig.ParseArgumentsError: Invalid token array (index-5919f5c9.js, line 141)
[Log] applying update: setSettings (index-5919f5c9.js, line 141)
[Warning] Command bash -lic 'alias' exited with exit code 0: bash: no job control in this shell (index-5919f5c9.js, line 67)

[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Warning] Command /bin/bash -lic 'fc -ln 1' exited with exit code 0: bash: no job control in this shell (index-5919f5c9.js, line 67)

[Warning] Command which fish exited with exit code 1: undefined (index-5919f5c9.js, line 67)
[Error] Fig.LoginShellError: Could not find executable for fish
	error
	captureError (index-5919f5c9.js:131:677078)
	(anonymous function) (index-5919f5c9.js:138:186)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Log] applying update: error (index-5919f5c9.js, line 141)
[Warning] Fig.ParseArgumentsError: Invalid token array (index-5919f5c9.js, line 141)
[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Log] applying update: setParserResult (index-5919f5c9.js, line 141)
[Error] TypeError: _.at is not a function. (In '_.at($)', '_.at' is undefined)
	Mi (index-5919f5c9.js:40:93352)
	(anonymous function) (index-5919f5c9.js:40:93575)
	ih (index-5919f5c9.js:38:74179)
	lk (index-5919f5c9.js:40:125735)
	jk (index-5919f5c9.js:40:125156)
	ik (index-5919f5c9.js:40:124697)
	Xk (index-5919f5c9.js:40:134595)
	Qk (index-5919f5c9.js:40:133959)
	Fk (index-5919f5c9.js:40:130546)
	Fk
	jg (index-5919f5c9.js:38:67440)
	(anonymous function) (index-5919f5c9.js:40:127929)`

**Comment by oilcake** [comment]
By the way - fig is really awesome, now I just can't imagine good life without out, so please fix! Lack of this feature may get people depressed! :)

**Comment by mschrage** [comment]
Can other people please post the logs from the web inspector view?

**Comment by mschrage** [comment]
Also can everyone try restarting their terminals and seeing the the bug persists afterwards (#2520)

**Comment by DTcloudOps** [comment]
[Log] [fig] declaring constants... (user-script:4, line 1)
[Log] [fig] setting up event listeners... (index-5919f5c9.js, line 67)
[Log] [fig] unsubscribing any existing notifications... (index-5919f5c9.js, line 67)
[Log] settingsFontSize – undefined (index-5919f5c9.js, line 185)
[Log] applying update: setUserFuzzySearchEnabled (index-5919f5c9.js, line 141)
[Log] applying update: error (index-5919f5c9.js, line 141)
[Warning] Fig.ParseArgumentsError: Invalid token array (index-5919f5c9.js, line 141)
[Log] applying update: setSettings (index-5919f5c9.js, line 141)
[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Warning] Command bash -lic 'alias' exited with exit code 0: bash: cannot set terminal process group (41377): Inappropriate ioctl for device (index-5919f5c9.js, line 67)
bash: no job control in this shell

[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Warning] Command /usr/local/bin/bash -lic 'fc -ln 1' exited with exit code 0: bash: cannot set terminal process group (41377): Inappropriate ioctl for device (index-5919f5c9.js, line 67)
bash: no job control in this shell

[Warning] Command which fish exited with exit code 1: undefined (index-5919f5c9.js, line 67)
[Error] Fig.LoginShellError: Could not find executable for fish
	error
	captureError (index-5919f5c9.js:131:677078)
	(anonymous function) (index-5919f5c9.js:138:186)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Log] applying update: setParserResult (index-5919f5c9.js, line 141)
[Warning] Command bash -lic 'alias' exited with exit code 0: bash: cannot set terminal process group (-1): Inappropriate ioctl for device (index-5919f5c9.js, line 67)
bash: no job control in this shell

[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Log] applying update: setParserResult (index-5919f5c9.js, line 141)

**Comment by duyhunter1001** [comment]
> Can other people please post the logs from the web inspector view?

here's the output from Webview inspect:

![image](https://github.com/withfig/fig/assets/44033926/90d7b0a2-9184-4071-bedc-280fd3da3dd6)

**Comment by muyiyr** [comment]
Same Here Mac 12.1

<img width="583" alt="Screen Shot 2023-05-12 at 10 55 26 AM" src="https://github.com/withfig/fig/assets/32588751/d74354e3-baf6-4f81-b9fa-c1d26225d30f">

**Comment by rickyadha** [comment]
Has anyone tried to reinstall this thing?

**Comment by licsth** [comment]
Same issue here on macOS 12.2.1 in fig version 2.16.0. Restarting the terminal or reinstalling fig (either with uninstall+install or force install) isn't fixing the issue

<img width="990" alt="Bildschirmfoto 2023-05-12 um 08 18 44" src="https://github.com/withfig/fig/assets/32680008/15dea3b6-318c-4b2a-a0b3-dfe420a86dc5">

**Comment by melvard** [comment]
Here is my log from inspector. Please, write down if there is anything helpful I provide for solving the issue. 

[Error] Fig.LoginShellError: Could not find executable for fish
(anonymous function) — index-5919f5c9.js:67:505203
(anonymous function) — index-5919f5c9.js:69:507160
asyncFunctionResume
[native code]
promiseReactionJobWithoutPromise
promiseReactionJob

	error
	captureError (index-5919f5c9.js:131:677078)
	(anonymous function) (index-5919f5c9.js:138:186)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
	


[Error] TypeError: _.at is not a function. (In '_.at($)', '_.at' is undefined)
App — index-5919f5c9.js:185:911917
Xh — index-5919f5c9.js:38:84588
dj — index-5919f5c9.js:40:96326
Vk — index-5919f5c9.js:40:133482
Uk — index-5919f5c9.js:40:133413
Jk — index-5919f5c9.js:40:133271
Ok — index-5919f5c9.js:40:129591
Fk — index-5919f5c9.js:40:130398
Fk
jg — index-5919f5c9.js:38:67440
(anonymous function) — index-5919f5c9.js:40:127929

	Mi (index-5919f5c9.js:40:93352)
	(anonymous function) (index-5919f5c9.js:40:93575)
	ih (index-5919f5c9.js:38:74179)
	lk (index-5919f5c9.js:40:125735)
	jk (index-5919f5c9.js:40:125156)
	ik (index-5919f5c9.js:40:124697)
	Xk (index-5919f5c9.js:40:134595)
	Qk (index-5919f5c9.js:40:133959)
	Fk (index-5919f5c9.js:40:130546)
	Fk
	jg (index-5919f5c9.js:38:67440)
	(anonymous function) (index-5919f5c9.js:40:127929)

**Comment by shvmsrma** [comment]
> Has anyone tried to reinstall this thing?

Yes i did, multiple times facing same issue

**Comment by FilipSwiatczak** [comment]
Mac Monterey 12.1 21C52 Intel Core i9
```
[Log] [fig] declaring constants... (user-script:4, line 1)
[Log] [fig] setting up event listeners... (index-5919f5c9.js, line 67)
[Log] [fig] unsubscribing any existing notifications... (index-5919f5c9.js, line 67)
[Log] settingsFontSize – undefined (index-5919f5c9.js, line 185)
[Log] applying update: setUserFuzzySearchEnabled (index-5919f5c9.js, line 141)
[Log] applying update: error (index-5919f5c9.js, line 141)
[Warning] Fig.ParseArgumentsError: Invalid token array (index-5919f5c9.js, line 141)
[Log] applying update: setSettings (index-5919f5c9.js, line 141)
[Warning] Command bash -lic 'alias' exited with exit code 0: bash: no job control in this shell (index-5919f5c9.js, line 67)

[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Warning] Command /bin/zsh -lic 'fc -R; fc -ln 1' exited with exit code 0: (anon):setopt:7: can't change option: monitor (index-5919f5c9.js, line 67)

[[31mERROR[39m]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  Add the following parameter to [4m~/.zshrc[24m for extra diagnostics on error:

    [1mGITSTATUS_LOG_LEVEL=DEBUG[0m

  Restart Zsh to retry gitstatus initialization:

    [32m[4mexec[24m[32m zsh[39m

[Warning] Error getting commands in history – TypeError: undefined is not an object (evaluating 'tt[tt.length-1].complete') (index-5919f5c9.js, line 136)
TypeError: undefined is not an object (evaluating 'tt[tt.length-1].complete')
[Warning] Command /bin/bash -lic 'fc -ln 1' exited with exit code 0: bash: no job control in this shell (index-5919f5c9.js, line 67)

[Warning] Command which fish exited with exit code 1: undefined (index-5919f5c9.js, line 67)
[Error] Fig.LoginShellError: Could not find executable for fish
	error
	captureError (index-5919f5c9.js:131:677078)
	(anonymous function) (index-5919f5c9.js:138:186)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Log] applying update: setParserResult (index-5919f5c9.js, line 141)
[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Log] applying update: setParserResult (index-5919f5c9.js, line 141)
[Log] applying update: setFigState (index-5919f5c9.js, line 141)
[Log] applying update: setParserResult (index-5919f5c9.js, line 141)
[Error] TypeError: _.at is not a function. (In '_.at($)', '_.at' is undefined)
	Mi (index-5919f5c9.js:40:93352)
	(anonymous function) (index-5919f5c9.js:40:93575)
	ih (index-5919f5c9.js:38:74179)
	lk (index-5919f5c9.js:40:125735)
	jk (index-5919f5c9.js:40:125156)
	ik (index-5919f5c9.js:40:124697)
	Xk (index-5919f5c9.js:40:134595)
	Qk (index-5919f5c9.js:40:133959)
	Fk (index-5919f5c9.js:40:130546)
	Fk
	jg (index-5919f5c9.js:38:67440)
	(anonymous function) (index-5919f5c9.js:40:127929)
```

**Comment by pkellz** [comment]
![image](https://github.com/withfig/fig/assets/4536756/2d2ab733-a2b5-45e6-8820-41cf19e2b7ec)

**Comment by anelrh26** [comment]
![image](https://github.com/withfig/fig/assets/2037428/c1ef10ec-0bb1-400c-8fba-f6afec3641d6)

**Comment by anelrh26** [comment]
This started working for me when I upgraded my MacOS to 13.3.1

**Comment by pkellz** [comment]
@anelrh26 me too, thanks

**Comment by DTcloudOps** [comment]
Are previous versions of MacOS to 13.3.1 not supported anymore?

**Comment by grant0417** [comment]
Can you try restarting Fig? Does this resolve the issue?

**Comment by mengqianyixing** [comment]
MacOS 13.3.1 (a) (22E772610a) this issue still exist.

**Comment by ginixsan** [comment]
![image](https://github.com/withfig/fig/assets/1665208/a0046b55-5daf-4c3d-92dd-f870e9a90bc9)

**Comment by iugo-robert** [comment]
I'm also having similar issues, see screenshot attached.
<img width="1112" alt="Screen Shot 2023-05-15 at 8 36 29 am" src="https://github.com/withfig/fig/assets/1051689/730d7905-2ca0-4358-8357-69592f2427a6">

**Comment by mobylin** [comment]
<img width="1016" alt="截圖 2023-05-15 下午1 07 08" src="https://github.com/withfig/fig/assets/4704378/0ed75e2b-81a0-42e7-bd6c-90d8ce4e9b4f">

**Comment by TheFe91** [comment]
> <img alt="截圖 2023-05-15 下午1 07 08" width="1016" src="https://user-images.githubusercontent.com/4704378/238248492-0ed75e2b-81a0-42e7-bd6c-90d8ce4e9b4f.png">

Same here!!

**Comment by duyhunter1001** [comment]
> This started working for me when I upgraded my MacOS to 13.3.1

me too. it's worked

**Comment by oilcake** [comment]
Started to work again after fig restart on the same macos Catalina, I am happy!

**Comment by shvmsrma** [comment]
worked for me tooooo, thank you so much !!!!

**Comment by TheFe91** [comment]
After restarting about 10 times it started to work again...very strange!

**Comment by WaldoDoesTech** [comment]
up and running! Fantastic!

**Comment by duyhunter1001** [comment]
**In summary, we can try the following two methods to fix the issue:**

1. Restart the fig a few times.
2. Upgrade macOS to the latest working version.

good luck for you :))

**Comment by paulashby** [comment]
fig restart worked for me on Catalina! Thank you very much!

**Comment by melvard** [comment]
works dudes)) fig restart

**Comment by DTcloudOps** [comment]
Confirmed Fig now working as expected, Thank you all!

**Comment by aschade92** [comment]
I'm having the same issue still, I have the latest version of osx and fig. Have tried restarting multiple times to no avail.

```
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /opt/homebrew/Cellar/fish/3.6.1/bin/fish
  - terminal: terminal
  - cwd: /Users/alexschade/Downloads
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_SET_PARENT: 04B0FB76-33D7-4B3A-98A2-B4CEC65B6D08
    - PATH: /Users/alexschade/.rbenv/shims:/opt/homebrew/bin:/Users/alexschade/.local/bin:/Users/alexschade/.fig/bin:/usr/local/munki:/opt/local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/local/bin:/usr/local/munki:/Users/alexschade/.fig/bin:/Users/alexschade/.local/bin
    - FIG_TERM: 2.16.0
    - SHELL: /opt/homebrew/bin/fish
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PARENT: 
    - FIGTERM_SESSION_ID: 38cde918-7211-4097-b273-d63b7b325c5b
    - TERM: xterm-256color
    - FIG_PID: 12541
```

fig debug output

[autocomplete.log.txt](https://github.com/withfig/fig/files/11636236/autocomplete.log.txt)
